saat başı stklara otomatik mail gönderim özelliği mailgun kutuphanesi…
acikkaynak/deprem-io-backend pull request #134
Opened 2023-02-11 17:24 UTC by mehmetik

… eklendi.

2023-02-11 17:25 UTC, mehmetik commented
Örnek ENV bilgisi @izzetemredemir 'ye verildi.

2023-02-11 17:33 UTC, mehmetik commented
linter'i çalıştırdığım halde geçemiyor testten? 

npm run lint && npm run format

> deprem-io-backend@1.0.0 lint
> rome check --apply-suggested .

Fixed 27 file(s) in 36ms

> deprem-io-backend@1.0.0 format
> rome format --write .

Formatted 27 file(s) in 48ms

@izzetemredemir @anonrig

2023-02-11 19:12 UTC, anonrig commented
`main` branch'teki hatalari cozdum. rebase edip gonderir misin bu branch'e?

2023-02-11 19:14 UTC, anonrig requested changes

2023-02-11 19:14 UTC, anonrig commented on index.js
> +setInterval(() => {
setInterval yerine `node-cron` gibi bir tool kullanmamiz gerekiyor.

2023-02-11 19:14 UTC, anonrig commented on package.json
> +    "mailgun-js": "^0.22.0",
bu yanlis kutuphane. official kutuphanesi `mailgun.js`

```
npm install mailgun.js
```

2023-02-11 19:14 UTC, anonrig commented on services/mail.js
> +  domain: process.env.MAILGUN_DOMAIN,
bunu `config.js` dosyasina tasiyalim lutfen.

2023-02-11 19:14 UTC, anonrig commented on services/mail.js
> +    to: process.env.MAIL_RECEIVERS || "mehmetik@gmail.com",
bunu `config.js` dosyasina tasiyalim lutfen.

2023-02-11 19:14 UTC, anonrig commented on services/yardimMails.js
> +    const str = `${process.env.MAIL_SUBJECT} - ${yardimTipi.toUpperCase()}`;
bunu `config.js` dosyasina tasiyalim lutfen.

2023-02-11 19:14 UTC, anonrig commented on services/yardimMails.js
> +    const to = process.env.MAIL_RECEIVERS;
bunu `config.js` dosyasina tasiyalim lutfen.

2023-02-11 19:16 UTC, mehmetik commented on services/yardimMails.js
> +    const to = process.env.MAIL_RECEIVERS;
Yapıyı değiştirdim biraz Son halini atınca tekrar gözden geçirmeni istiyeceğim hocam nodemailler ile SMTP üstünden gönderim yapacağız

2023-02-11 19:34 UTC, anonrig requested changes

2023-02-11 19:34 UTC, anonrig commented on index.js
> +  setInterval(() => {
`setInterval` yerine `node-cron` kullanalim.

2023-02-11 19:34 UTC, anonrig commented on services/yardimMails.js
> +    },
bunlarin hepsi `config.js` icersinde olmali

2023-02-11 19:34 UTC, anonrig commented on services/yardimMails.js
> +      rejectUnauthorized: false,
bunu neden false dedik?

2023-02-12 15:58 UTC, izzetemredemir approved these changes

2023-02-12 19:02 UTC, merged